# Generated by Django 4.0.4 on 2022-05-23 17:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredientamount_amount_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#F29C1B', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
